export const plantOptions = [
    { value: "", english: "Select a plant", urdu: "پودا منتخب کریں", prefixes: [] },
    { value: "Maize", english: "Maize", urdu: "مکئی", prefixes: ["Corn"] },
    { value: "Chickpeas", english: "Chickpeas", urdu: "چنے", prefixes: ["Chickpea", "ChickPea"] },
    { value: "Mango", english: "Mango", urdu: "آم", prefixes: ["Mango"] },
    { value: "Rice", english: "Rice", urdu: "چاول", prefixes: ["Rice"] }
];

export const textContent = {
    english: {
        welcome: "AI Plant Disease Predictor",
        selectImage: "Select an image",
        selectPlant: "Select Plant",
        startAnalyzing: "Start Analyzing",
        processing: "Processing...",
        chatTitle: "Ask About Results",
        chatSubtitle: "Ask questions about the detected diseases",
        analyzeFirst: "Upload an image, select a plant, and click 'Start Analyzing' to begin.",
        placeholder: "Ask a question...",
        tryAsking: "Try asking",
        you: "You",
        assistant: "AI Assistant",
        thinking: "AI is thinking",
        analyzing: (plant) => `Analyzing your ${plant} leaf image...`,
        error: "Sorry, I encountered an error. Please try again.",
        initialAnalysisPrompt: "Analyze these plant disease predictions and provide a helpful summary for the farmer.",
        suggestedPrompts: ["Tell me more about this disease", "How do I treat this?", "What are the symptoms?", "Is this serious?"],
        location: "Location",
        gettingLocation: "Getting location...",
        locationAccess: "Allow location access for local recommendations",
        enableLocation: "Enable Location",
        locationError: "Location access denied or unavailable",
        chatHistory: "Chat History",
        newChat: "New Chat",
        noChats: "No previous chats",
        deleteChat: "Delete chat",
        currentChat: "Current Chat",
        collapseSidebar: "Collapse sidebar",
        expandSidebar: "Expand sidebar"
    },
    urdu: {
        welcome: "پلانٹ ڈیزیز پریڈکٹر",
        selectImage: "تصویر منتخب کریں",
        selectPlant: "پودا منتخب کریں",
        startAnalyzing: "تجزیہ شروع کریں",
        processing: "جاری ہے...",
        chatTitle: "نتائج کے بارے میں پوچھیں",
        chatSubtitle: "پائی گئی بیماریوں کے بارے میں سوالات پوچھیں",
        analyzeFirst: "شروع کرنے کے لیے تصویر اپ لوڈ کریں، پودا منتخب کریں، اور 'تجزیہ شروع کریں' پر کلک کریں۔",
        placeholder: "سوال پوچھیں...",
        tryAsking: "کوشش کریں",
        you: "آپ",
        assistant: "AI معاون",
        thinking: "سوچ رہا ہوں",
        analyzing: (plant) => `آپ کی ${plant} کی پتی کی تصویر کا تجزیہ کیا جا رہا ہے...`,
        error: "معذرت، کچھ مسئلہ پیش آیا۔ براہ کرم دوبارہ کوشش کریں۔",
        initialAnalysisPrompt: "ان پلانٹ ڈیزیز پیشنگوئیوں کا تجزیہ کریں اور کسان کے لیے مددگار خلاصہ پیش کریں۔",
        suggestedPrompts: ["اس بیماری کے بارے میں مزید بتائیں", "علاج کیا ہے؟", "علامات کیا ہیں؟", "کیا یہ سنگین ہے؟"],
        location: "مقام",
        gettingLocation: "مقام حاصل کیا جا رہا ہے...",
        locationAccess: "مقامی سفارشات کے لیے مقام تک رسائی کی اجازت دیں",
        enableLocation: "مقام فعال کریں",
        locationError: "مقام تک رسائی مسترد یا دستیاب نہیں",
        chatHistory: "چیٹ تاریخ",
        newChat: "نیا چیٹ",
        noChats: "کوئی پچھلی چیٹس نہیں",
        deleteChat: "چیٹ حذف کریں",
        currentChat: "موجودہ چیٹ",
        collapseSidebar: "سائیڈبار بند کریں",
        expandSidebar: "سائیڈبار کھولیں"
    }
};